### ISSUE TITLE
NameError: name 'simple_thermostat' is not defined

### ISSUE THREAD

**Issue by mrwulff** [vegascom-jeff/nvenergy#2]
Awesome work.  I have been waiting on this for a while.  However it does not work.

Error while setting up nvenergy platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nvenergy/climate.py", line 72, in setup_platform
    nve_thermostat = NVEThermostat(simple_thermostat)
NameError: name 'simple_thermostat' is not defined

**Comment by vegascom-jeff** [comment]
Well that is embarrassing! That's what I get for making a last minute code change.

Should be fixed now. You'll need to download and replace the updated climate.py file in /config/custom_components/nvenergy.

**Comment by mrwulff** [comment]
awesome.  works great.
